AWSTemplateFormatVersion: 2010-09-09  
  
Parameters:  
  Stage:  
    Type: String  
  accountPrimaryReadCUnits:  
    Type: String  
  accountPrimaryWriteCUnits:  
    Type: String  
  accountGSISKReadCUnits:  
    Type: String  
  accountGSISKWriteCUnits:  
    Type: String  
  
  enablePointRecovery:
    Default: false
    Type: String
    AllowedValues: [true, false]

Conditions: 
  pointInTimeRecovery: !Equals [ !Ref enablePointRecovery, true ]

Resources:  
  account:  
    Type: 'AWS::DynamoDB::Table'  
    Properties:  
      AttributeDefinitions:  
        - AttributeName: PK  
          AttributeType: S  
        - AttributeName: SK  
          AttributeType: S  
      KeySchema:  
        - AttributeName: PK  
          KeyType: HASH  
        - AttributeName: SK  
          KeyType: RANGE  
      ProvisionedThroughput:  
        ReadCapacityUnits: !Ref accountPrimaryReadCUnits  
        WriteCapacityUnits: !Ref accountPrimaryWriteCUnits 
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [pointInTimeRecovery, true, false]
      TableName: account  
      GlobalSecondaryIndexes:  
        - IndexName: SK-index  
          KeySchema:  
            - AttributeName: SK  
              KeyType: HASH   
          Projection:  
            ProjectionType: ALL  
          ProvisionedThroughput:  
            ReadCapacityUnits: !Ref accountGSISKReadCUnits  
            WriteCapacityUnits: !Ref accountGSISKWriteCUnits